### ISSUE TITLE
Enable ASCII coutdown in smaller terminal windows

### ISSUE THREAD

**Issue by silentjay** [pando85/timer#49]
Be nice if the ASCII countdown could be used in smaller terminal windows if possible? I like to have a tmux pane dedicated to a timer but don't want it taking up too much screen real estate.

**Comment by pando85** [comment]
Hello @silentjay. The counter resizes itself depending of the size of the window. What do you mean in particular?

**Comment by silentjay** [comment]
Sorry I wasn't more clear. Under a certain terminal size the counter changes from ASCII countdown to regular text. Would be nice if it could use a smaller ASCII format for smaller terminal windows.

**Comment by pando85** [comment]
Now I understood. I'm not against that kind of feature but, right now, I don't have time to dedicate to this project. I will mark it as `good first issue`. Thank you :)
