### ISSUE TITLE
[NEW] Add many timers

### ISSUE THREAD

**Issue by lyz-code** [pando85/timer#57]
**Is your feature request related to a problem? Please describe.**
I want to start many timers, right now I need to open a terminal for each of them and run the command

**Describe the solution you'd like**
timer could accept many timer arguments for example:

```bash
timer 10:00 13:30 17:30
```

Once 10:00 arrive, they will run the bell and set the next timer

**Describe alternatives you've considered**
* Doing a bash function that wraps it all
* Do a terminal user interface that lets you create many timers

```bash
timer tui
> Time: 10:00
> Label: Do X
> Time: 13:00
> Label: Do Y
> (press q)
```

**Additional context**

**Comment by lyz-code** [comment]
Another possibility maybe more interesting is that it opens the $EDITOR and allows you to write a file with the next syntax:

```
10:15: Thing A

13:30: Thing B
14:15: Thing C
14:15: Thing D

16:00: Thing F
```

**Comment by pando85** [comment]
This `timer 10:00 13:30 17:30` should be equivalent to something like this `timer 10:00 && timer 13:30 && timer 17:30`, no?
Actually, I don't want to expend time adding features, but this can be easy.

I like the idea of keeping timer simple but we can handle multiple of these issues by creating a new binary with more complex functionality, like the timer-ui that you mentioned there.
