### ISSUE TITLE
[NEW] Run the terminal bell

### ISSUE THREAD

**Issue by lyz-code** [pando85/timer#58]
**Is your feature request related to a problem? Please describe.**
I prefer visual bells than audio ones.

**Describe the solution you'd like**
A terminal configuration so that instead of running a sound or the pc speaker it runs the terminal bell, like `echo -e \a`

```bash
timer --visual 10:00
```

**Describe alternatives you've considered**

```bash
timer 10:00 & echo -e \a
```

**Additional context**
Add any other context about the feature request here.

**Comment by pando85** [comment]
This one is interesting, I would try to prioritize this.
