### ISSUE TITLE
[BUG] Too many 88 in the output

### ISSUE THREAD

**Issue by lyz-code** [pando85/timer#59]
**Describe the bug**
The number 88 is not a nice one and the output is filled with it:

**To Reproduce**
```bash
timer 4h2m
```

**Expected behavior**
Don't use the number 88 so much

**Command output**

```

         ,d8    88                ad888888b,                              88          ,d8
       ,d888    88               d8"     "88                            ,d88        ,d888
     ,d8" 88    88                       a8P                          888888      ,d8" 88
   ,d8"   88    88,dPPYba,            ,d8P"   88,dPYba,,adPYba,           88    ,d8"   88    ,adPPYba,
 ,d8"     88    88P'    "8a         a8P"      88P'   "88"    "8a          88  ,d8"     88    I8[    ""
 8888888888888  88       88       a8P'        88      88      88          88  8888888888888   `"Y8ba,
          88    88       88      d8"          88      88      88          88           88    aa    ]8I
          88    88       88      88888888888  88      88      88          88           88    `"YbbdP"'
```

**Additional context**
https://en.wikipedia.org/wiki/88_%28number%29#In_white_nationalism_and_supremacism

**Comment by pando85** [comment]
I can understand your concern but that's not intended. We use [figlet univers](http://www.figlet.org/fontdb_example.cgi?font=univers.flf and it is provided by them.

Anyway, we could change that 88 for something similar but BB is not as symmetric as 88 and HH could sound even worse.

**Comment by lyz-code** [comment]
I see your point looking at possible alternatives I see we're fucked:

* KKK
* XXX

Maybe `Q` `9`?
